name: Test DevContainer Build

on:
  push:
    branches: [main, test-gh-action-for-devcontainer]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: "true"
